### ISSUE TITLE
New rule: Layout/ArgumentAlignment

### ISSUE THREAD

**Issue by NJRBailey** [qmee/dev-public-utils#9]
```yaml
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
```
From this:
```ruby
Lop.publish("event_name",
            {
              a: "a",
              b: "b",
            }
)
```
to this:
```ruby
Lop.publish("event_name",
  {
    a: "a",
    b: "b",
  }
)
```

Admittedly we might want to enforce all variables on a new line in a multiline, which would mean we just need to add the rule `Style/FirstMethodArgumentLineBreak`. This would result in:
```ruby
Lop.publish(
  "event_name",
  {
    a: "a",
    b: "b",
  }
)
```
Let me know what you think

**Comment by JonCooper1994** [comment]
I prefer that third style personally

**Comment by NJRBailey** [comment]
> I prefer that third style personally

I agree, will open a ticket for that and close this for now

**Comment by NJRBailey** [comment]
@JonCooper1994 Let me know what you think of the new suggestion https://github.com/qmee/dev-public-utils/issues/21
